export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
export const RESET_REGISTER_USER = 'RESET_REGISTER_USER';

export const VERIFY_EMAIL_REQUEST = 'VERIFY_EMAIL_REQUEST';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_CLEAR = 'LOGIN_USER_CLEAR';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const GET_JOB_REQUEST = 'GET_JOB_REQUEST';
export const GET_JOB_SUCCESS = 'GET_JOB_SUCCESS';
export const GET_JOB_FAILURE = 'GET_JOB_FAILURE';

export const GET_JOB_REQUEST_BY_ID = 'GET_JOB_REQUEST_BY_ID';
export const GET_JOB_SUCCESS_BY_ID = 'GET_JOB_SUCCESS_BY_ID';
export const GET_JOB_FAILURE_BY_ID = 'GET_JOB_FAILURE_BY_ID';
export const CLEAR_JOB_DETAILS = 'CLEAR_JOB_DETAILS';

export const SET_JOB_PROPOSAL = 'SET_JOB_PROPOSAL';

export const ADD_JOB_PROPOSAL_REQUEST = 'ADD_JOB_PROPOSAL_REQUEST';
export const ADD_JOB_PROPOSAL_SUCCESS = 'ADD_JOB_PROPOSAL_SUCCESS';
export const ADD_JOB_PROPOSAL_FAILURE = 'ADD_JOB_PROPOSAL_FAILURE';
export const GET_PROPOSAL_BY_JOB_REQUEST = 'GET_PROPOSAL_BY_JOB_REQUEST';
export const GET_PROPOSAL_BY_JOB_SUCCESS = 'GET_PROPOSAL_BY_JOB_SUCCESS';

export const GET_PROPOSAL_REQUEST = 'GET_PROPOSAL_REQUEST';
export const GET_PROPOSAL_SUCCESS = 'GET_PROPOSAL_SUCCESS';

export const SET_JOB_FAVOURITE = 'SET_JOB_FAVOURITE';

export const GET_ALL_TECHNOLOGY = 'GET_ALL_TECHNOLOGY';
export const SET_ALL_TECHNOLOGY = 'SET_ALL_TECHNOLOGY';
export const GET_ALL_TECHNOLOGY_FAILURE = 'GET_ALL_TECHNOLOGY_FAILURE';
export const CREATE_JOB_POST = 'CREATE_JOB_POST';
export const JOB_CREATED_SUCCESSFULLY = 'JOB_CREATED_SUCCESSFULLY';
export const JOB_CREATION_ERROR = 'JOB_CREATION_ERROR';
export const CLEAR_JOB_CREATION = 'CLEAR_JOB_CREATION';
export const UPDATE_JOB_POST_REQUEST = 'UPDATE_JOB_POST_REQUEST';
export const UPDATE_JOB_POST_SUCCESS = 'UPDATE_JOB_POST_SUCCESS';

export const GET_TIMEZONE_REQUEST = 'GET_TIMEZONE_REQUEST';
export const GET_TIMEZONE_SUCCESS = 'GET_TIMEZNOE_SUCCESS';
export const GET_TIMEZONE_FAILURE = 'GET_TIMEZONE_FAILURE';

// ==========client company registration type=================
export const CLIENT_REGISTRATION_COMPANY_REQUEST = ' CLIENT_REGISTRATION_COMPANY_REQUEST';
export const CLIENT_REGISTRATION_COMPANY_SUCCESS = 'CLIENT_REGISTRATION_COMPANY_SUCCESS';
export const CLIENT_REGISTRATION_COMPANY_FAILURE = 'CLIENT_REGISTRATION_COMPANY_FAILURE';
export const UPDATE_REGISTRATION_COMPANY_REQUEST = ' UPDATE_REGISTRATION_COMPANY_REQUEST';
export const RESET_REGISTRATION_COMPANY_STATUS = 'RESET_REGISTRATION_COMPANY_STATUS';

export const REGISTRATION_ADDRESS_REQUEST = 'REGISTRATION_ADDRESS_REQUEST';
export const REGISTRATION_ADDRESS_SUCCESS = 'REGISTRATION_ADDRESS_SUCCESS';
export const REGISTRATION_ADDRESS_FAILURE = 'REGISTRATION_ADDRESS_FAILURE';
export const UPDATE_REGISTRATION_ADDRESS_REQUEST = 'UPDATE_REGISTRATION_ADDRESS_REQUEST';
export const RESET_REGISTRATION_ADDRESS_STATUS = 'RESET_REGISTRATION_ADDRESS_STATUS';

export const REGISTRATION_DIGITAL_PRESENCE_REQUEST = 'REGISTRATION_DIGITAL_PRESENCE_REQUEST';
export const REGISTRATION_DIGITAL_PRESENCE_SUCCESS = 'REGISTRATION_DIGITAL_PRESENCE_SUCCESS';
export const REGISTRATION_DIGITAL_PRESENCE_FAILURE = 'REGISTRATION_DIGITAL_PRESENCE_FAILURE';
export const UPDATE_REGISTRATION_DIGITAL_PRESENCE_REQUEST =
  'UPDATE_REGISTRATION_DIGITAL_PRESENCE_REQUEST';
export const RESET_REGISTRATION_DIGITAL_PRESENCE_STATUS =
  'RESET_REGISTRATION_DIGITAL_PRESENCE_STATUS';

export const RESENT_VERIFY_EMAIL_REQUEST = 'RESENT_VERIFY_EMAIL_REQUEST';
export const RESENT_VERIFY_EMAIL_SUCCESS = 'RESENT_VERIFY_EMAIL_SUCCESS';
export const GET_PRIMARY_SKILLS = 'GET_PRIMARY_SKILLS';
export const GET_PRIMARY_SKILLS_SUCCESS = 'GET_PRIMARY_SKILLS_SUCCESS';
export const GET_PRIMARY_SKILLS_FAILURE = 'GET_PRIMARY_SKILLS_FAILURE';
export const SAVE_SELECTED_SKILL = 'SAVE_SELECTED_SKILL';
export const SAVE_SELECTED_SKILL_FAILURE = 'SAVE_SELECTED_SKILL_FAILURE';

export const SAVE_SKILL_EXPERIENCE = 'SAVE_SKILL_EXPERIENCE';
export const SAVE_SKILL_EXPERIENCE_FAILURE = 'SAVE_SKILL_EXPERIENCE_FAILURE';

export const RESET_ERROR = 'RESET_ERROR';
export const RESEND_VERIFY_EMAIL_REQUEST = 'RESEND_VERIFY_EMAIL_REQUEST';
export const RESEND_VERIFY_EMAIL_SUCCESS = 'RESEND_VERIFY_EMAIL_SUCCESS';
export const RESEND_VERIFY_EMAIL_FAILURE = 'RESEND_VERIFY_EMAIL_FAILURE';
export const RESET_RESEND_VERIFY_EMAIL_STATUS = 'RESET_RESEND_VERIFY_EMAIL_STATUS';

/** Coder Profile Fetch */
export const GET_CODER_PROFILE = 'GET_CODER_PROFILE';
export const GET_CODER_PROFILE_SUCCESS = 'GET_CODER_PROFILE_SUCCESS';
export const GET_CODER_PROFILE_FAILURE = 'GET_CODER_PROFILE_FAILURE';

export const GET_CODER_ADDRESS = 'GET_CODER_ADDRESS';
export const GET_CODER_ADDRESS_SUCCESS = 'GET_CODER_ADDRESS_SUCCESS';
export const GET_CODER_ADDRESS_FAILURE = 'GET_CODER_ADDRESS_FAILURE';

export const GET_CODER_DIGITAL_PRESENCE = 'GET_CODER_DIGITAL_PRESENCE';
export const GET_CODER_DIGITAL_PRESENCE_SUCCESS = 'GET_CODER_DIGITAL_PRESENCE_SUCCESS';
export const GET_CODER_DIGITAL_PRESENCE_FAILURE = 'GET_CODER_DIGITAL_PRESENCE_FAILURE';

export const GET_ALL_RECOMMENDED_TECH = 'GET_ALL_RECOMMENDED_TECH';
export const GET_ALL_RECOMMENDED_TECH_SUCCESS = 'GET_ALL_RECOMMENDED_TECH_SUCCESS';
export const GET_ALL_RECOMMENDED_TECH_FAILURE = 'GET_ALL_RECOMMENDED_TECH_FAILURE';

export const GET_RECOMMENDED_CODER_REQUEST = 'GET_RECOMMENDED_CODER_REQUEST';
export const GET_RECOMMENDED_CODER_SUCCESS = 'GET_RECOMMENDED_CODER_SUCCESS';
export const GET_RECOMMENDED_CODER_FAILURE = 'GET_RECOMMENDED_CODER_FAILURE';
export const GET_CODER_SKILLS_AND_EXPERIENCE = 'GET_CODER_SKILLS_AND_EXPERIENCE';
export const GET_CODER_SKILLS_AND_EXPERIENCE_SUCCESS = 'GET_CODER_SKILLS_AND_EXPERIENCE_SUCCESS';
export const GET_CODER_SKILLS_AND_EXPERIENCE_FAILURE = 'GET_CODER_SKILLS_AND_EXPERIENCE_FAILURE';

export const GET_CODER_EDUCATIONAL_QUALIFICATION = 'GET_CODER_EDUCATIONAL_QUALIFICATION';
export const GET_CODER_EDUCATIONAL_QUALIFICATION_SUCCESS =
  'GET_CODER_EDUCATIONAL_QUALIFICATION_SUCCESS';
export const GET_CODER_EDUCATIONAL_QUALIFICATION_FAILURE =
  'GET_CODER_EDUCATIONAL_QUALIFICATION_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const RESET_PASSWORD_UPDATE = 'RESET_PASSWORD_UPDATE';
export const SET_TECHNOLOGY_NAME = 'SET_TECHNOLOGY_NAME';

export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS';
export const COMPANY_DETAILS_SUCCESS = 'COMPANY_DETAILS_SUCCESS';
export const COMPANY_DETAILS_FAILURES = 'COMPANY_DETAILS_FAILURE';

export const GET_CLIENT_PROFILE_DATA_BY_ID = 'GET_CLIENT_PROFILE_DATA_BY_ID';
export const GET_CLIENT_PROFILE_DATA = 'GET_CLIENT_PROFILE_DATA';
export const GET_CLIENT_PROFILE_DATA_SUCCESS = 'GET_CLIENT_PROFILE_DATA_SUCCESS';
export const GET_CLIENT_PROFILE_DATA_FAILURES = 'GET_CLIENT_PROFILE_DATA_FAILURE';

export const GET_ADMIN_DATA_REQUEST = 'GET_ADMIN_DATA_REQUEST';
export const GET_ADMIN_DATA_SUCCESS = 'GET_ADMIN_DATA_SUCCESS';
export const GET_ADMIN_DATA_FAILURE = 'GET_ADMIN_DATA_FAILURE';

export const GET_TnC = 'GET_TnC';
export const GET_TnC_SUCCESS = 'GET_TnC_SUCCESS';
export const GET_TnC_FAIURES = 'GET_TnC_FAIURES';
export const GET_TnC_REQUEST = 'GET_TnC_REQUEST';
